dist: trusty
sudo: false
language: cpp
addons:
  apt:
    sources:
    - llvm-toolchain-trusty-5.0
    packages:
    - clang-5.0
script:
- CXX=/usr/bin/clang++-5.0 CC=/usr/bin/clang-5.0 cmake .
- cmake --build .
- cpack
deploy:
  provider: bintray
  file: deploy.json
  user: ithamsteri
  key: $BINTRAY_API_KEY
  passphrase: $PGPKEY
