dist: trusty
sudo: required
language: cpp
addons:
  apt:
    sources:
    - llvm-toolchain-trusty-5.0
    packages:
    - clang-5.0
    - libboost-test-dev
script:
- CXX=/usr/bin/clang++-5.0 CC=/usr/bin/clang-5.0 cmake .
- cmake --build .
- ctest -V
- cpack
- sudo dpkg -i helloworld-*.deb
- helloworld
deploy:
  provider: bintray
  file: deploy.json
  user: ithamsteri
  key: $BINTRAY_API_KEY
  passphrase: $PGPKEY
